name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest

    step:
    - uses: actions/checkout@v2
    - name: docker login
      env:
        DOCKER_USER: ${{secrets.DOCKER_USER}}
        DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
      run:
        docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
    steps:    
      -name: Build the Docker image
       run: docker build . --file hello-github-actions/action-a/Dockerfile --tag testgitHub:${{secrets.DOCKER_TAG}}:$(date + %s)
    step:  
      -name: Docker push
       run: docker push ${{secrets.DOCKER_TAG}}:$(date)
